### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by Crossshield45** [htr-tech/host#17]
I tryed to host a html file using this but it shows this screen
![Screenshot_20230309-145501_Chrome](https://user-images.githubusercontent.com/118594491/223975640-a6b3a84d-c61c-4204-8045-733080d945b2.jpg)

Please fix it @htr-tech

**Comment by Kawsar-Hosen** [comment]
Paid

**Comment by Crossshield45** [comment]
What??

**Comment by Crossshield45** [comment]
What did you mean? @rifat935

**Comment by htr-tech** [comment]
enter the correct path where your webpage are located..

OR You can also do it manually

Go to the destination folder & start a php server `php -S 127.0.0.1:5858` Then Manually Forward port by cloudflared
