### ISSUE TITLE
perhaps one line command ?

### ISSUE THREAD

**Issue by changchichung** [htr-tech/host#8]
is it possible to pass hosting/port into script and get the url ?
like
```
bash host.sh localhostrun 8765
```

thanks for the great script!

**Comment by htr-tech** [comment]
maybe not .. i will soon add some more tunneling option & remove the serveo & localhostrun

**Comment by ZekePolarisBSH** [comment]
I wish serveo worked.

**Comment by htr-tech** [comment]
> I wish serveo worked.

serveo is down

**Comment by ZekePolarisBSH** [comment]
I know, but maybe someone can bring it back like they did kinda with Mega.
